#!/bin/bash
# clone repo (with name as directory) from your bitbucket 

# Usage:
#	cd <root dir of prj> # directory can't be under git control
#	run the script
#	enter bitbucket username and password

[[ "$GITUSER" == "" ]] && echo "\$GITUSER not defined!" && exit

echo CLONE remote repo to local folder


to_dir="${PWD##*/}"
echo -n Enter password for $GITUSER: && read -s PASSWORD && echo
cd ..
git clone https://$GITUSER@bitbucket.org/$GITUSER/$to_dir.git $to_dir
#git clone ssh://git@bitbucket.org/$GITUSER/$to_dir.git $to_dir
#https://$GITUSER@bitbucket.org/$GITUSER/$to_dir.git $to_dir
#MIIEoQIBAAKCAQEAm3HtgiJEcz780OmM/Jv65LQ/VQcp7ChtVceUwAudC6cy2o6v

#EWfJO5NSVrYhSC/CG6X2ShU0NfsqEs2AkZCisPOCxf8UWL454g==
cd $to_dir

