#!/bin/bash
# Makes a non git directory to a new private bitbucket repository with all files added to initial commit
# Usage = enter your bitbucket GITUSER and password in the script

[[ "$GITUSER" == "" ]] && echo "\$GITUSER not defined!" && exit

echo -n Enter password for $GITUSER: && read -s PASSWORD && echo

echo "git init..."
if [ -d ".git" ]; then
	echo "Already exist"
  else
	git init
  fi

echo "add readme.md..."
if [ -f "readme.md" ]; then
	echo "Already exist"
  else
	echo "#About" > readme.md
  fi

echo "add license..."
if [ -f "license" ]; then
	echo "Already exist"
  else
	echo "LGPL3" > license
	# TODO: host
	# TODO: user (author)
	# TODO: limits
  fi

echo "git add -A ..."
git add -A .

echo "Initial commit..."
git commit -m "Initial commit"

echo "...creating new remote repo on bitbucket with name ${PWD##*/}"
curl --user $GITUSER:$PASSWORD https://api.bitbucket.org/1.0/repositories/ --data name=${PWD##*/} --data is_private='true' -k -s | jq ''

echo "adding new repo remote URL https://$GITUSER@bitbucket.org/$GITUSER/ ..."
git remote add bb https://$GITUSER@bitbucket.org/$GITUSER/${PWD##*/}.git
#git remote add origin ssh://git@bitbucket.org/$GITUSER/${PWD##*/}.git

echo "git push -u origin ..."
git push -u bb master
#git push -u bb --all #upstream
#git push -u bb --tags

#if https repo raise: fatal: could not read Password for 'https://bisoff@bitbucket.org': No such file or directory
#try this:
#git config --global credential.helper wincred # save pwd at windows pwd store
#git config --global core.askpass /usr/libexec/git-core/git-gui--askpass #ask pwd if missed


