#!/bin/sh
# deletes remote repo

[[ "$GITUSER" == "" ]] && echo "\$GITUSER not defined!" && exit

echo DELETE: remote repo; local repo

[[ "$GITUSER" = "" ]] && echo "\$GITUSER is not defined ! (Use varadd)" && exit 1

echo -n Enter password for $GITUSER: && read -s PASSWORD && echo

echo DELETING remote repo ...
#curl -X DELETE --user $GITUSER:$PASSWORD https://api.bitbucket.org/1.0/user/repositories/ --data name=${PWD##*/}
# | jq '.[] | .name + " - " + if .is_private then "private" else "" end'
repo=${PWD##*/}
curl --user $GITUSER:$PASSWORD -X DELETE "https://bitbucket.org/api/2.0/repositories/$GITUSER/$repo" -s | jq ''

echo deleting local repo ...
#git remote remove origin
cd ..
rm -dfv "$repo"
