#!/bin/sh
[[ "$GITUSER" == "" ]] && echo "\$GITUSER not defined!" && exit

echo DELETE repo ssh-key
[[ "$1" = "" ]] && echo key_id is missed && exit 1
echo -n Enter password for $GITUSER: && read -s PASSWORD && echo
echo deleting repo ssh-key ...
#DELETE /users/{accountname}/ssh-keys/{key_id}
curl --user $GITUSER:$PASSWORD -X DELETE https://bitbucket.org/api/1.0/users/$GITUSER/ssh-keys/$1 -s | jq ''


