#!/bin/sh

[[ "$SVN_USER" == "" ]] && echo "\$SVN_USER not defined!" && exit

echo CLONE remote repo to local folder

[[ "$SVN_REPOS" = "" ]] && echo "Var SVN_REPOS is not detected ! Run at first: . varadd SVN_REPOS '<url>'" && exit 1

#todo: test for empty curr_dir
echo -n Enter password for $SVN_USER: && read -s PASSWORD && echo
curr_dir=${PWD##*/}

echo "CLONING repo $SVN_REPOS/svn/$curr_dir..."
cd ..
svn checkout --username="$SVN_USER" --password="$PASSWORD" "$SVN_REPOS/svn/$curr_dir"
cd $curr_dir
