#!/bin/sh
# Makes a non git directory to a new private bitbucket repository with all files added to initial commit
# Usage = enter your bitbucket username and password in the script

[[ "$GITUSER" == "" ]] && echo "\$GITUSER not defined!" && exit

echo CLONE remote repo to local folder
[[ "$1" != "" ]] && TMP_GITUSER=$1 || TMP_GITUSER=$GITUSER

TO_DIR="${PWD##*/}"
if [[ "$1" = "" ]]; then # own repo
	echo -n Enter password for $TMP_GITUSER: && read -s PASSWORD && echo
	cd ..
	#git clone git@github.com/$GITUSER/$TO_DIR.git $TO_DIR
	git clone https://$TMP_GITUSER:$PASSWORD@github.com/$TMP_GITUSER/$TO_DIR.git
	#git clone ssh://git@github.com/$GITUSER/$TO_DIR.git $TO_DIR
  else
	cd ..
	git clone https://github.com/$TMP_GITUSER/$TO_DIR.git $TO_DIR
  fi
cd $TO_DIR

