#!/bin/sh
# Makes a non git directory to a new private bitbucket repository with all files added to initial commit
# Usage = enter your bitbucket GITUSER and password in the script

[[ "$GITUSER" == "" ]] && echo "\$GITUSER not defined!" && exit

echo -n Enter password for $GITUSER: && read -s PASSWORD && echo

echo "git init..."
git init

echo "#About" > readme.md
#echo "LGPL3" > license
#TODO IF

echo "git add -A ..."
git add -A .

echo "Initial commit..."
git commit -m "Initial commit"

echo "...creating new remote repo on github with name '${PWD##*/}'"
curl -u $GITUSER:$PASSWORD https://api.github.com/user/repos -k -d '{"name":"'${PWD##*/}'"}' -k -s | jq '.[] | .name + if .private then " - private" else "" end'
#--data {"private":true} -s

echo "adding new repo remote URL  https://github.com/$GITUSER/${PWD##*/}.git ..."
git remote add gh https://github.com/$GITUSER/${PWD##*/}.git
#git remote add origin ssh://git@bitbucket.org/$GITUSER/${PWD##*/}.git

#echo "git push -u gh --all..."
echo "git push .."
#git push -u gh --all # -u: upstream
#git push -u gh --tags
git push gh master
git push gh --tags
#git push origin -u

#git remote add gh  https://github.com/bisoff/utils-vcs.git
