#!/bin/sh
# Makes a non git directory to a new private bitbucket repository with all files added to initial commit
# Usage = enter your bitbucket username and password in the script

[[ "$GITUSER" == "" ]] && echo "\$GITUSER not defined!" && exit

echo "DELETE: remote repo; local repo"

[[ "$GITUSER" = "" ]] && echo "\$GITUSER is not defined ! (Use varadd)" && exit 1

echo -n Enter password for $GITUSER: && read -s PASSWORD && echo

echo DELETING remote repo ...
repo=${PWD##*/}
curl -u $GITUSER:$PASSWORD -X DELETE "https://api.github.com/repos/$GITUSER/$repo" -k
#| jq ''

echo deleting local repo ...
git remote remove orig_gh
cd ..
rm -dfv "$repo"
