#!/bin/bash
# pdel -n=<prj> -p=<path> -s=<set>

utility_path=$(echo "`dirname \"$0\"`")
# shift loop
# if $path == "" then pwd
# if $prj == "" then folder
# if $set == "" then default

# loop set of prj (if $1 == "" then default)
# if prj == $prj then rm
# extract path
# if path == $path then rm

