#!/bin/bash
# ped [<list>]
# edit default or specified repo list

utility_path=$(echo "`dirname \"$0\"`")

# get host
host="$(cat $utility_path/.cfg/default.cfg | sed -E -n "s/^host=([^#]*)/\1/p")" # host alias
#echo host:$host

# get prj list
repos=$1
if [[ "$repos" == "" ]]; then
	repos="$(cat $utility_path/.cfg/default.cfg | sed -E -n "s/^default_list=([^#]*)/\1/p")"
 fi

ed $repos
