#!/bin/bash
# . pgo <repo> <list>

repo="$1"
[[ "$repo" == "" ]] && echo "[GO TO PROJECT] repo name is missed !"

utility_path=$(echo "`dirname \"$(which pgo))\"`")

# get host
host="$(cat $utility_path/.cfg/default.cfg | sed -E -n "s/^host=([^#]*)/\1/p")" # host alias
#echo host:$host

# get repo list
repos=$1
if [[ "$repos" == "" ]]; then
	repos="$(cat $utility_path/.cfg/default.cfg | sed -E -n "s/^default_list=([^#]*)/\1/p")"
 fi

# find prj in list
# TODO: test $repo exists
# extract path
path="$(cat $utility_path/.cfg/$host/$repo | sed -E -n "s/^path=([^#]*)/\1/p")"
# echo path: $path
# TODO: test $path exists
cd $path
