#!/bin/bash
# . pgo <repo> <in_list?>

. lib-prj

# test 1st param - repo name
p_repo="$1"
[[ "$p_repo" == "" ]] && echo "[GO TO PROJECT] repo name is missed !"

home=$(home) # echo home: $home
host=$(host) # echo host: $host
repos=$1; repos=$(get_repos $repos) # echo repos: $repos


for repo_loop in $(cat $home/.cfg/$host/$repos.list | tr -d '\r'); do 
	repo_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$repo_loop | tr -d '\r'`
  done

# extract path of repo
repo_path="$(sed -E -n 's/^path=([^#]*)/\1/p' $home/.cfg/$host/$p_repo | tr -d '\r')" # echo repo_path: $repo_path

# go to prj
# ??TODO: test $path exists
eval cd "$path"
