#!/bin/bash 
# plist <list>

. lib-prj
home=$(home) # echo home: $home
host=$(host) # echo host: $host
repos=$1; repos=$(get_repos $repos) 
#echo REPO LIST: $repos
echo "========= $repos ========="

for repo in $(cat $home/.cfg/$host/$repos.list | tr -d '\r' | sort); do 
	path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$repo | tr -d '\r'` # sed -E -n 's/^path=([^#]+)/\1/p' /Users/a.bysov/prj/utils-vcs/.cfg/ok/ue
	( # to return curr path
	echo -e "$repo:\t$path"
	)
  done

