#!/bin/bash
# pren <prj> [<list>] 		# CASE #1 - rename prj name (find prj by curr_path)
# pren <prj> [<list>] 		# CASE #2 - upd path of prj (find prj by name)
# pren -n=<prj> -p=<path> -t=<type> -r=<remote> -s=<set>

prj=$1
[[ "$prj" == "" ]] && echo "[PROJECT RENAME] prj name is missed !" && exit
list=$2

#new_path=$(pwd) #; echo new_path: $new_path
new_path="${PWD/#$HOME/~}" # replace $HOME to ~

# TODO: detect repo type (git/svn/hg - .git foder / .svn folder? / ..) and exit if new_path not a repo 

. lib-prj
home=$(home) # echo home: $home
host=$(host) # echo host: $host

if [[ "$list" == "" ]]; then
	prj_list=$(get_repos).list 
  else
  	prj_list="$list.list"
  fi
# echo "prj_list: $prj_list"
# TODO: test prj in list
#exit

# CASE #1 - rename prj 
curr_path=$(pwd)
prj_name=$(find_prj_by_path "$home/.cfg/$host" $curr_path) #; echo prj_name: $prj_name	 #old prj name
[[ $prj_name == "" ]] && echo "[PROJECT RENAME] Project file not found " && exit
prj_file=$home/.cfg/$host/$prj_name
#prj_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$prj | tr -d '\r'` #; echo curr_path: $prj_path
mv "$prj_file" "$home/.cfg/$host/$prj" || exit
#echo "list: $home/.cfg/$host/$prj_list"
sed -i "s/^$prj_name\$/$prj/g" "$home/.cfg/$host/$prj_list" || exit # sed -i "s/^jr$/jrhw/g" `echo $home/.cfg/$host/$(get_repos).list`

# TODO: CASE #2 - rename prj path
#prj_file=$home/.cfg/$host/$prj
#[[ ! -f $prj_file ]] && echo "[PROJECT RENAME] Project is absent" && exit

#echo "path=$new_path" 	>  $prj_path
#echo "type=git" 	>> $prj_file
#echo "remote=" 		>> $prj_file

plist

# TODO: if file exists but absenr in default list then add

# shift loop
# if $prj == "" then folder
# if $path == "" then pwd
# if $type == "" then git
# if $remote == "" then current
# if $set == "" then default

