#!/bin/bash
# psavall <list> <msg> # save every prj in list (add/commit/push)

list=$1
msg=$2

. lib-prj
home=$(home) 			# echo home: $home
host=$(host) 			# echo host: $host
[[ "$list" == "." ]] && list="" # trik to save default
[[ "$list" == "" ]] && list=$(get_repos)
# echo list: $list  		# get default repos list

for prj in $(cat $home/.cfg/$host/$list.list | tr -d '\r'); do 
	path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$prj | tr -d '\r'` # sed -E -n 's/^path=([^#]+)/\1/p' /Users/a.bysov/prj/utils-vcs/.cfg/ok/ue
	(
	eval cd "$path"
	changes=$(gis | wc -l)	# echo changes: $changes
	echo -e "\n${grey_back}$prj: $path${norm}"
	if [ $changes -ne 0 ]; then
		gok "$msg" # TODO: переделать на использование либы 
		echo
	  fi
	#${red}none${norm}"
	)
  done

# TODO: test uncommited (untracked, changed, deleted, staged)



