#!/bin/bash 
# plist <list>

. lib-prj
home=$(home) # echo home: $home
host=$(host) # echo host: $host
repos=$1; repos=$(get_repos $repos) # echo repos: $repos

for prj in $(cat $home/.cfg/$host/$repos.list | tr -d '\r'); do 
	path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$prj | tr -d '\r'` # sed -E -n 's/^path=([^#]+)/\1/p' /Users/a.bysov/prj/utils-vcs/.cfg/ok/ue
	
	(
	eval cd "$path"
	changes=$(gis | wc -l)	# echo changes: $changes
	if [ $changes -eq 0 ]; then
		echo -e "${grey}$prj: $path${norm}"
	  else
		echo -e "\n${grey_back} $prj: $path ${norm}"
		git status -s --untracked-files
		echo
	  fi
	)
  done

