#!/bin/bash 
# plist <list>

. lib-prj
home=$(home) # echo home: $home
host=$(host) # echo host: $host
repos=$1; repos=$(get_repos $repos) # echo repos: $repos

for repo in $(cat $home/.cfg/$host/$repos.list | tr -d '\r'); do 
	path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$repo | tr -d '\r'` # sed -E -n 's/^path=([^#]+)/\1/p' /Users/a.bysov/prj/utils-vcs/.cfg/ok/ue
	
	(	echo "$repo: $path"; \
		eval cd "$path"; \
		git status -s --untracked-files; \
		echo \
	)
  done

