#!/bin/bash
# psync <prj> <msg> # a) fix prj when need (add/commit) 2) pull when need  3) push when need

# test 1st param - repo name
prj=$1
msg=$2

. lib-prj
home=$(home) 			# echo home: $home
host=$(host) 			# echo host: $host

if [[ "$prj" != "" ]]; then 
  else
	curr_path=$(pwd) #; echo cur_path:$curr_path # replace 
	prj_name=$(find_prj_by_path "$home/.cfg/$host" $curr_path) #; echo prj_name: $prj_name
	[[ "$prj_name" == "" ]] && echo "[PROJECT SYNC] project name is missed  and  not found by 'path=' in $home/.cfg/$host !" && exit
  fi

# TODO: get prj vcs_type (svn, git)
# TODO: get prj remote

( # to return current path
echo "$prj: $prj_path"
eval cd "$prj_path"
echo "prj_name: $prj_name"
# fix prj when need (add/commit) 
l "$msg" 

# pull when need  
gul

# push when need
gus
exit
)



# TODO: test uncommited (untracked, changed, deleted, staged)



