#!/bin/bash
utility_path=$(echo "`dirname \"$0\"`")

# test prj file
# get prj path
# TODO: get prj vcs_type (svn, git)
# get prj remote

# TODO: test uncommited (untracked, changed, deleted, staged)
# push
